### ISSUE TITLE
PlayerShops v1.2.4 not working 1.16.5

### ISSUE THREAD

**Issue by shiqutong** [Blackixx/BSP-PlayerShops#6]
[10:21:10] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'playershops' in plugin PlayerShops v1.2.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-434]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-434]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-434]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 50 out of bounds for length 9
	at java.util.Arrays$ArrayList.get(Arrays.java:4351) ~[?:?]
	at net.minecraft.server.v1_16_R3.NonNullList.get(SourceFile:46) ~[patched_1.16.5.jar:git-Paper-434]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventoryCustom$MinecraftInventory.getItem(CraftInventoryCustom.java:72) ~[patched_1.16.5.jar:git-Paper-434]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[patched_1.16.5.jar:git-Paper-434]
	at org.black_ixx.bossshop.managers.ShopCustomizer.addItem(ShopCustomizer.java:191) ~[?:?]
	at org.black_ixx.bossshop.managers.ShopCustomizer.createInventory(ShopCustomizer.java:155) ~[?:?]
	at org.black_ixx.bossshop.managers.ShopCustomizer.createInventory(ShopCustomizer.java:41) ~[?:?]
	at org.black_ixx.bossshop.core.BSShop.createInventory(BSShop.java:198) ~[?:?]
	at org.black_ixx.bossshop.core.BSShop.openInventory(BSShop.java:293) ~[?:?]
	at org.black_ixx.bossshop.core.BSShop.openInventory(BSShop.java:268) ~[?:?]
	at org.black_ixx.bossshop.addon.playershops.managers.PlayerShopsManager.openShoplist(PlayerShopsManager.java:155) ~[?:?]
	at org.black_ixx.bossshop.addon.playershops.managers.CommandManager.onCommand(CommandManager.java:34) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-434]
	... 19 more

**Comment by shiqutong** [comment]
[10:19:41] [Craft Scheduler Thread - 2/WARN]: [BossShopPro] Plugin BossShopPro v2.0.9 generated an exception while executing task 32
java.lang.NullPointerException: null
	at org.black_ixx.bossshop.addon.playershops.objects.PlayerShopItem.createShopItemNormal(PlayerShopItem.java:149) ~[?:?]
	at org.black_ixx.bossshop.addon.playershops.managers.ShopCreator.createShop(ShopCreator.java:73) ~[?:?]
	at org.black_ixx.bossshop.addon.playershops.objects.PlayerShop.createShop(PlayerShop.java:170) ~[?:?]
	at org.black_ixx.bossshop.addon.playershops.managers.SaveManager.loadShop(SaveManager.java:55) ~[?:?]
	at org.black_ixx.bossshop.addon.playershops.managers.PlayerShopsManager.loadFile(PlayerShopsManager.java:75) ~[?:?]
	at org.black_ixx.bossshop.addon.playershops.managers.PlayerShopsManager.loadFile(PlayerShopsManager.java:70) ~[?:?]
	at org.black_ixx.bossshop.addon.playershops.managers.PlayerShopsManager.loadFile(PlayerShopsManager.java:70) ~[?:?]
	at org.black_ixx.bossshop.addon.playershops.managers.PlayerShopsManager.init(PlayerShopsManager.java:59) ~[?:?]
	at org.black_ixx.bossshop.addon.playershops.PlayerShops.load(PlayerShops.java:90) ~[?:?]
	at org.black_ixx.bossshop.addon.playershops.PlayerShops.bossShopFinishedLoading(PlayerShops.java:58) ~[?:?]
	at org.black_ixx.bossshop.managers.ClassManager.setupDependentClasses(ClassManager.java:176) ~[?:?]
	at org.black_ixx.bossshop.BossShop$1.run(BossShop.java:79) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-434]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-434]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-434]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by MonzterDev** [comment]
Can confirm, this issue is also prevalent for me as well.

**Comment by matteof04** [comment]
This issue can be fixed by merging #5

**Comment by MonzterDev** [comment]
> This issue can be fixed by merging #5

Thank you very much!
